version: "2"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      GOLD_ESCROW_BOT_TOKEN: 7832141748:AAHjN2gPEI2PrU5v1LzMS01lQHeHKEg34-g
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: pass
      DATABASE_URL: postgresql://user:pass@postgres:5432/db
      MNEMONIC: "symbol beef post shuffle problem fox pear peace comic neck hurdle cute"
      MASTER_KEY: Ym2Z0T20AkJ9ErEKXJWmczOKL16z15PahG+OIUfeZ9o=
    ports:
      - "3000:3000"
      - "5555:5555"  # Expose Prisma Studio port
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./package.json:/usr/src/app/package.json
      - ./nodemon.json:/usr/src/app/nodemon.json
    command: >
      sh -c "npx prisma migrate dev --name init && npx prisma generate && yarn dev"  # Run migrations before starting the app

  postgres:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

# For production, you could use Docker secrets to store sensitive values.
# Uncomment and use the following block for that purpose.

# secrets:
#   gold_escrow_bot_token:
#     file: ./secrets/gold_escrow_bot_token.txt
