version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      GOLD_ESCROW_BOT_TOKEN: ${GOLD_ESCROW_BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      MNEMONIC: ${MNEMONIC}
      MASTER_KEY: ${MASTER_KEY}
    ports:
      - "3000:3000"